[package]
name = "ps-util"
description = "This crate aims to provide generally helpful utility functions and traits."
version = "0.1.0-1"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
