[package]
name = "ps-util"
version = "0.1.0-8"
edition = "2021"
rust-version = "1.93"
description = "This crate aims to provide generally helpful utility functions and traits."
documentation = "https://docs.rs/ps-util"
readme = "README.md"
repository = "https://github.com/prokopschield/ps-util"
license = "GPL-3.0-or-later"
keywords = ["array", "slice", "utility"]
categories = ["data-structures", "rust-patterns"]

[dependencies]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
